### ISSUE TITLE
Centrifuge platform demo script design tasks

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1944]
[Script](https://docs.google.com/document/d/1u7xxVnnb_dnVTCKu_tM2TmHRNAiA_qmlmC02NWeOI1E/edit)
[Video material](https://www.figma.com/file/129zYScuYj54HJnIKRQgjM/Video-material?type=design&node-id=0-1&mode=design&t=bbDyo9ZxbfV0Omta-0)
[Storyboard](https://www.figma.com/file/lPlMldT54SVz4kxslO8DWg/Storyboard?type=design&node-id=3-16&mode=design&t=7G4ZS0DdvgvXbUHA-0)

## Pool overview
- [x] Pool overview with [Asad pool suggestions](https://www.figma.com/file/lPlMldT54SVz4kxslO8DWg?node-id=17:8929&mode=design#709814530) including fake pool icons for the different categories

## Portfolio
- [x] Allocation chart: [Font and font size suggestion](https://www.figma.com/file/129zYScuYj54HJnIKRQgjM?node-id=80:1867&mode=design#711093988)
- [x] Allocation chart: [Tab suggestion](https://www.figma.com/file/129zYScuYj54HJnIKRQgjM?node-id=80:1867&mode=design#711095438)
- [x] Transaction history: remove asset Id and add token price and token amount
- [x] Update correct data for holdings, overview and chart(Anna)
- [x] Update Transaction history data (Anna)

## Pool overview
- [x] Remove Anemoy logo and name and replace with fake pool logo
- [x] [Add updated info for key metrics](https://www.figma.com/file/129zYScuYj54HJnIKRQgjM?node-id=1:6418&mode=design#709203210)
- [x] Pool analysis: remove Fang's image and replace with stock photo 
- [x] Pool analysis: add text block for filler copy
- [x] Cashflow chart: Select 30 day filter instead of YTD
- [x] Cashflow chart: Principal payment and Fee payment has the same yellow status chip
- [x] Update correct data (Anna)

## NAV Management
- [x] Update to latest design

## Data layer
- [x] No design in Figma yet --> create design?
- [x] Remove Anemoy data

**Comment by TimHoub** [comment]
'Cashflow chart: Principal payment and Fee payment has the same yellow status chip' -> Is this an issue? I thought we could have the outgoing cashflows as yellow, if we really want we can use the red one for fees?
