### ISSUE TITLE
Data Protocol: Verify and implement P2P Communication

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/apps#2050]
Interactions with the new data protocol should happen on a p2p basis. Currently, the connections to the POD are based on normal web2 interfaces with a mix of web3 signing (jwt token with crypto accounts signing). 

We are facing two bigger problems here: 
* Current apps code is based around `polkadot-js`
* We need to use a custom p2p protocol for the data protocol - making the usage of `polkadot-api` most likely not feasible for the data protocol BUT probably needed for the transactions part (unless we code that part ourselves)

The goal of this issue is that the UI is able to communicate with a data node via the data protocol.

## Tasks
The following tasks are just a first draft on the rough steps needed to fulfil the above goal.
* [x] Verify the UI can connect the the kademlia network - i.e. use libp2p with kademlia and connect to bootnodes
* [x] Try submitting messages to the network via the p2p layer
* [ ] Research if `polkadot-api` can be extended with other protocols 
* [ ] Research if we should switch the UI to `polkadot-api` already
* [ ] Research how data protocol and `polkadot-api`/`polkadot-js` can live side by side in `centrifuge-js`
   *NOTE: `centrifuge-js` must be usable by third parties to talk to the data protocol too, without having knowledge about the p2p network part.*
* [ ] Implementation of the core p2p parts - i.e. mostly submitting the messages specced [here](https://centrifuge.hackmd.io/bojp3cHzRYG-oiOuHvXeoQ?view#Messages)

## Resources
* New, light-client first polkadot-api (longterm replacement for polkadot-js) [here](https://github.com/polkadot-api/polkadot-api)
* Libp2p JS implementation [here](https://github.com/libp2p/js-libp2p)
