### ISSUE TITLE
feat: Extend onchain attestation

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/apps#2557]
The current onchain closed [here](https://github.com/centrifuge/apps/issues/2431) needs some adjustments. 

## Tasks
* [ ] Include `onchainReserve` in the `assets`-section - TAKE from runtimeApi `Nav.reserve`
* [ ] Include ALL assets in the `assets`-section - currently, cash items are missing
* [ ] Include total accrued-unpaid fees as 1 asset item - `price = -1` with right decimals, TAKE from runtimeApi `Nav.navFees`
* [ ] Adjust `quantity` field to pool decimals - currently, it is 18 decimals
* [ ] Change `asset` structure 
   * [ ] `asset` &rarr; `assetId` - `0` for `onchainReserve`
   * [ ] New `asset` &rarr; `name` retrieved for the asset from ipfs data, `onchainReserve` for `onchainReserve`
* [ ] Remove `netFeeValue`
* [ ] Add "tokenAddresses" &rarr; list addresses of tranche tokens on the relevant networks, identified by `chainId` - see json for details 
* [ ] Add `timestamp` when this was signed to `portfolio` - unix timestamp in seconds
* [ ] Adapt `signature` to be a struct containing `signature` and `publicKey` of signer
* [ ] Ensure `netAssetValue`  is correct - TAKE from runtimeApi `Nav.total`

## Resources
[adjustedAttestation.json](https://github.com/user-attachments/files/18165999/adjustedAttestation_json.json)
